version: "3.8"

services:
  postgresdb:
    image: postgres
    container_name: postgresdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
    volumes:
      - ./script/init.sql:/docker-entrypoint-initdb.d/init.sql
    # secrets:
    #   - postgres-passwd
    # depends_on:
    #   - container_such_sql_server

# secrets:
#   postgres-passwd:
#     file: ./my_secret.env